"""Interactive setup wizard for Calmmage Sleep Challenge Bot.

Walks through every required env var one by one, respects values already in .env,
and writes the final configuration to .env at the repo root.

Run:
    uv run python setup_wizard.py           # interactive
    uv run python setup_wizard.py --force   # re-prompt even for already-set values
    uv run python setup_wizard.py --yes     # accept defaults for unset values without prompting
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

REPO_ROOT = Path(__file__).resolve().parent
ENV_PATH = REPO_ROOT / ".env"


@dataclass
class EnvVar:
    key: str
    prompt: str
    default: str | None = None
    secret: bool = False
    required: bool = False
    section: str = "General"
    validator: Callable[[str], str | None] | None = None  # returns error str or None


def _validate_token(v: str) -> str | None:
    if ":" not in v or len(v) < 20:
        return "Bot tokens look like '1234567:ABC…' (from @BotFather)."
    return None


def _validate_int(v: str) -> str | None:
    try:
        int(v)
    except ValueError:
        return "Expected an integer."
    return None


def _validate_phone(v: str) -> str | None:
    if not v.startswith("+") or not v[1:].replace(" ", "").isdigit():
        return "Use international format, e.g. +41772184188."
    return None


KEY_VARS: list[EnvVar] = [
    EnvVar(
        key="TELEGRAM_BOT_TOKEN",
        prompt="Telegram bot token from @BotFather",
        required=True,
        secret=True,
        section="Key variables",
        validator=_validate_token,
    ),
    EnvVar(
        key="BOTSPOT_ADMINS_STR",
        prompt="Admin usernames (comma-separated, e.g. '@petrlavrov')",
        default="@petrlavrov",
        section="Key variables",
    ),
    EnvVar(
        key="BOTSPOT_MONGO_DATABASE_CONN_STR",
        prompt="MongoDB connection string",
        default="mongodb://localhost:27017",
        section="Key variables",
    ),
    EnvVar(
        key="BOTSPOT_MONGO_DATABASE_DATABASE",
        prompt="MongoDB database name",
        default="sleep-challenge",
        section="Key variables",
    ),
]

SERVICE_ACCOUNT_VARS: list[EnvVar] = [
    EnvVar(
        key="BOTSPOT_TELETHON_MANAGER_API_ID",
        prompt="Telethon api_id (my.telegram.org) — leave blank to skip 'last seen' polling",
        default="",
        section="Telethon (optional — for 'last seen' bonus)",
        validator=lambda v: None if v == "" else _validate_int(v),
    ),
    EnvVar(
        key="BOTSPOT_TELETHON_MANAGER_API_HASH",
        prompt="Telethon api_hash — leave blank to skip",
        default="",
        secret=True,
        section="Telethon (optional — for 'last seen' bonus)",
    ),
    EnvVar(
        key="BOTSPOT_TELETHON_MANAGER_SESSIONS_DIR",
        prompt="Directory for Telethon session files",
        default="sessions",
        section="Telethon (optional — for 'last seen' bonus)",
    ),
]

# Fixed enable flags. The wizard writes them automatically — no prompt.
STATIC_FLAGS: dict[str, str] = {
    "BOTSPOT_MONGO_DATABASE_ENABLED": "true",
    "BOTSPOT_SCHEDULER_ENABLED": "true",
    "BOTSPOT_USER_DATA_ENABLED": "true",
    "BOTSPOT_USER_DATA_MIDDLEWARE_ENABLED": "true",
    "BOTSPOT_ASK_USER_ENABLED": "true",
    "BOTSPOT_SEND_SAFE_ENABLED": "true",
    "BOTSPOT_ERROR_HANDLER_ENABLED": "true",
    "BOTSPOT_BOT_COMMANDS_MENU_ENABLED": "true",
    "BOTSPOT_TELETHON_MANAGER_AUTO_AUTH": "true",
}


def _telethon_enabled(values: dict[str, str]) -> str:
    """Telethon_manager only enables when both api_id AND api_hash are filled;
    otherwise botspot's initialize() would assert-crash at startup."""
    has_id = bool(values.get("BOTSPOT_TELETHON_MANAGER_API_ID", "").strip())
    has_hash = bool(values.get("BOTSPOT_TELETHON_MANAGER_API_HASH", "").strip())
    return "true" if (has_id and has_hash) else "false"


def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    result: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if v.startswith('"') and v.endswith('"'):
            v = v[1:-1]
        result[k.strip()] = v
    return result


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by setup_wizard.py — edit freely, re-run wizard to update.",
        "",
        "# ========== Key variables (must be set) ==========",
    ]
    for var in KEY_VARS:
        v = values.get(var.key, "")
        lines.append(
            f'{var.key}="{v}"' if v and (" " in v or "@" in v) else f"{var.key}={v}"
        )
    lines.append("")
    lines.append("# ========== Telethon (optional — 'last seen' polling) ==========")
    for var in SERVICE_ACCOUNT_VARS:
        v = values.get(var.key, "")
        lines.append(f"{var.key}={v}")
    lines.append("")
    lines.append("# ========== Botspot enable flags (auto-managed) ==========")
    for k, v in STATIC_FLAGS.items():
        lines.append(f"{k}={v}")
    lines.append(f"BOTSPOT_TELETHON_MANAGER_ENABLED={_telethon_enabled(values)}")
    lines.append("")
    path.write_text("\n".join(lines) + "\n")


def _mask(value: str) -> str:
    if len(value) <= 4:
        return "****"
    return value[:2] + "…" + value[-2:]


def _prompt(var: EnvVar, current: str | None, force: bool, yes: bool) -> str:
    shown_current = _mask(current) if (current and var.secret) else (current or "")
    default = var.default or ""
    has_value = bool(current) and current != ""

    if yes and has_value and not force:
        return current  # type: ignore[return-value]

    if has_value and not force:
        return current  # type: ignore[return-value]

    hint_parts = []
    if has_value:
        hint_parts.append(f"current: {shown_current}")
    if default:
        hint_parts.append(f"default: {default}")
    hint = f"  [{' · '.join(hint_parts)}]" if hint_parts else ""

    while True:
        sys.stdout.write(f"\n{var.prompt}{hint}\n> ")
        sys.stdout.flush()
        try:
            raw = input()
        except EOFError:
            if var.required and not default:
                print(f"\n{var.key} is required and cannot be set non-interactively.")
                sys.exit(2)
            raw = ""
        value = raw.strip()
        if value == "" and has_value and not force:
            return current  # type: ignore[return-value]
        if value == "":
            value = default
        if var.required and value == "":
            print(f"  {var.key} is required.")
            continue
        if var.validator and value:
            err = var.validator(value)
            if err:
                print(f"  {err}")
                continue
        return value


def _section(name: str) -> None:
    print(f"\n─── {name} " + "─" * max(1, 60 - len(name)))


def run_wizard(force: bool, yes: bool) -> None:
    print("Calmmage Sleep Challenge Bot — setup wizard")
    print(f"Writing to: {ENV_PATH}")
    current = _read_env_file(ENV_PATH)

    values: dict[str, str] = dict(current)

    current_section = None
    for var in KEY_VARS + SERVICE_ACCOUNT_VARS:
        if var.section != current_section:
            _section(var.section)
            current_section = var.section
        values[var.key] = _prompt(var, current.get(var.key), force, yes)

    for k, v in STATIC_FLAGS.items():
        values.setdefault(k, v)

    _write_env_file(ENV_PATH, values)

    print("\n✅ Wrote .env")
    print("\nNext steps:")
    print("  1. Start MongoDB  (docker compose up -d mongodb)")
    print("  2. Run the bot    (make run  or  uv run python src/bot.py --debug)")
    if not values.get("BOTSPOT_TELETHON_MANAGER_API_ID"):
        print("  3. Telethon skipped — 'last seen' polling disabled.")
    else:
        print(
            "  3. In DM with the bot (as admin): /setup_telethon\n"
            "     Paste the service phone (+41772184188), code, and 2FA password if set."
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Interactive setup wizard.")
    parser.add_argument(
        "--force", action="store_true", help="Re-prompt even for already-set values."
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Accept defaults without prompting (for non-interactive).",
    )
    args = parser.parse_args()
    run_wizard(force=args.force, yes=args.yes)


if __name__ == "__main__":
    main()
